nanfree: true
do_voxel_filter: true
do_ground_ground_segmentation: false
ground_pcls_voxelized: false
ground_threshold: 0.05
update_rate_hz: 10.0
resolution_x: 0.025
resolution_y: 0.025
resolution_z: 0.025