LocalPlanner:
  max_linear_vel: 0.2
  min_linear_vel: 0.0
  max_rotation_vel: 0.4
  max_in_place_rotation_vel: 0.35
  min_rotation_vel: 0.0
  yaw_goal_tolerance: 0.05
  yaw_start_tolerance: 0.25
  xy_goal_tolerance: 0.05
  heading_lookahead: 0.3
  num_window_points: 10
  holonomic_robot: true