TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.0
  max_rotational_vel: 0.3
  min_in_place_rotational_vel: 0.3
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: true
