sudo: required
dist: trusty
language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 libarmadillo-dev libarmadillo4 libboost1.54-all-dev
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - printenv
  - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp
install:
  - mkdir build && cd build && cmake -DDEBUG=OFF -DPROFILE=OFF .. && make -j2

script:
  - travis_wait 30 ./bin/mlpack_test -p

notifications:
  email:
    - mlpack-git@lists.mlpack.org
  irc:
    - "chat.freenode.net#mlpack"
