obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.16
inflation_radius: 0.6

observation_sources: scan distance_sensors distance_sensors_clearing

scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
distance_sensors: {sensor_frame: base_link, data_type: PointCloud, topic: distance_sensors, marking: true, clearing: false, obstacle_range: 0.4, raytrace_range: 0.4, observation_persistence: 5.0 }
distance_sensors_clearing: {sensor_frame: base_link, data_type: PointCloud, topic: distance_sensors_clearing, marking: false, clearing: true, raytrace_range: 5.0, observation_persistence: 0.0 }